# Generated by Django 6.0.7 on 2026-07-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycompany',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('assigned', 'Assigned to Delivery Person'), ('picked_up', 'Picked Up from Seller'), ('in_transit', 'In Transit'), ('near_destination', 'Near Destination'), ('delivered', 'Delivered')], default='assigned', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='checkout.order')),
            ],
        ),
    ]
