# Generated by Django 6.0.7 on 2026-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_deliverycompany_website_deliverytracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
        migrations.AddField(
            model_name='order',
            name='shop_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=-1.2855, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shop_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=36.8261, max_digits=9, null=True),
        ),
    ]
